### ISSUE TITLE
Passing additional arguments to interp

### ISSUE THREAD

**Issue by karthik** [hadley/lazyeval#28]
Filing this based on an email discussion. Details and an example are here: https://gist.github.com/karthik/ff8b44d41e16c84b5837#file-quantiles-r-L15-L16

The issue is that it isn't currently possible to pass on additional arguments to functions inside interp.

**Comment by hadley** [comment]
Yes - this is a fundamental limitation of interp. If you want to add extra arguments, you need to use another function.  I'll think about as part of #36
