### ISSUE TITLE
all_dots changes names to utf-8 in Windows

### ISSUE THREAD

**Issue by hkjinlee** [hadley/lazyeval#29]
Related to https://github.com/hadley/dplyr/issues/866.

I understand this encoding issue comes from R's default implementation of combining list, but hope there'd be a way to resolve this.

```{r}
> dots1 <- lazy_dots(한=1)
> names(dots1)
[1] "한"
> Encoding(names(dots1))
[1] "unknown"
> dots2 <- all_dots(dots1, 한=2)
> Encoding(names(dots2))
[1] "UTF-8" "UTF-8"
```

**Comment by hadley** [comment]
Why do you not want everything in UTF-8?
