### ISSUE TITLE
Should lazy_eval() allow for data to be an environment?

### ISSUE THREAD

**Issue by rpruim** [hadley/lazyeval#33]
I'm wondering if there is a good reason not to allow `data` to be an environment in `lazy_eval()`.

Changing
```r
    if (!is.null(data)) {
        eval(x$expr, data, x$env)
    }
```
to 
```r
    if (!is.null(data)) {
        eval(x$expr, as.list(data), x$env)
    }
```
should not change anything when `data` is a list or a data frame but would make it easy to write functions with a `data` argument that defaults to `parent.env()` (or anything else that reasonably coerces to a list, I guess.)

**Comment by hadley** [comment]
I'd rather force people to do this explicitly - otherwise the semantics aren't clear.
