### ISSUE TITLE
Lazyeval needs a quasiquoter

### ISSUE THREAD

**Issue by hadley** [hadley/lazyeval#36]
Also needs to work when things to interp are formulas, e.g.

```R
x <- 10
y <- 10
interp(~ .(x) + .(y))

interp(~ x + y, list(x = ~10, y = ~z))
# Bit awkward with operator precedence :/
interp(~ lm(f, data = mpg), list(f = ~ (y ~ x)))
``

**Comment by hadley** [comment]
Probably better to have quasiquoter with unquote operator

**Comment by hadley** [comment]
Also need some one to merge in extra arguments - i.e. something like [unquote-splicing](http://axisofeval.blogspot.com.au/2013/04/a-quasiquote-i-can-understand.html).

**Comment by jimhester** [comment]
Why did you decide to use `(( ))` and `({ })` rather than `.()` as `bquote()` does?

Using `.()` allows `.data$.(x)` to parse as valid code so you don't have to fallback to using 
```r
`$`(.data, ((x)))
```

**Comment by hadley** [comment]
@jimhester lets chat about this today. It's not too late to change, but I do quite like the current look. (One problem with `.` is that it's getting overloaded in a _lot_ of places)
