### ISSUE TITLE
lazy-and-lazy-eval-from-lazyeval-package

### ISSUE THREAD

**Issue by andreaspano** [hadley/lazyeval#57]
As suggested by krlmlr on http://stackoverflow.com/questions/36137399/lazy-and-lazy-eval-from-lazyeval-package I am adding this as an issue.

If I write:

```
> lazy_1 <- lazy(x+y, env = globalenv())
> lazy_1
<lazy>
  expr: x + y
  env:  <environment: R_GlobalEnv>
> x <- 1 ; y <- 2
> lazy_eval(lazy_1)
[1] 3

```
This makes sense to me as globalenv() is the environment in which to evaluate the expression as states by ?lazy

But when I write:

```
> rm(list = ls())
> env_2 <- new.env()
> env_2$x <- 6
> env_2$y <- 3
> lazy_2 <- lazy(x+y, env = env_2)
> lazy_2
<lazy>
  expr: x + y
  env:  <environment: R_GlobalEnv>
> lazy_eval(lazy_2)
Error in eval(expr, envir, enclos) : object 'x' not found
I would expect the same behavior from globalenv and env_2
```

Note that if I force the structure of lazy_2 as I assumed it should have been:

```
> lazy_2$env <- env_2
> lazy_eval(lazy_2)
[1] 9
```

everything works fine.

**Comment by hadley** [comment]
This way of using lazyeval is going to go away in the future, so I'm unlikely to bother fixing this bug.
