### ISSUE TITLE
lazy_dots loses env when something else is done w/ ...

### ISSUE THREAD

**Issue by jread-usgs** [hadley/lazyeval#61]
I couldn't find mention of this in the docs, and thought it was a bit confusing. I turned this into the simplest example I could come up with:

```r
eg1 <- function(...){
    lazy_eval(lazy_dots(...))
}
eg2 <- function(...){
    print(names(list(...)))
    lazy_eval(lazy_dots(...))
}

eg1(from = 2*pi)
$from
[1] 6.283185

eg2(from = 2*pi)
[1] "from"
 Error in eval(expr, envir, enclos) : could not find function "*" 
```

in e1, things work as expected, but in eg2, the env for the expression ends up being NULL, so it fails to find `*`:

```r
# eg1
$from
<lazy>
  expr: 2 * pi
  env:  <environment: R_GlobalEnv>

attr(,"class")
[1] "lazy_dots"

# eg2:
$from
<lazy>
  expr: 2 * pi
  env:  NULL

attr(,"class")
[1] "lazy_dots"

```

Apologies if this is a misunderstanding of how `...` works, but I thought I could send those off to multiple functions within a function and doing so wouldn't impact the result of the second one.

**Comment by hadley** [comment]
After an promise has been forced, you can't access the environment. You'll need to capture lazy dots before forcing the promise.
