### ISSUE TITLE
introduce lhs_eval() and rhs_eval() or add an argument to `f_eval()`

### ISSUE THREAD

**Issue by rpruim** [hadley/lazyeval#64]
`f_eval()` "evaluates" a formula.  It was designed thinking the the formula came from `f_capture()` and so only had a rhs.  But formulas in general also have a lhs, so it would be nice to be able to evaluate that as well.

Here are two possible solutions:

 1. Create `lhs_eval()` and `rhs_eval()`.  `rhs_eval <- f_eval` is essentially an alias for the current function that only evaluates the rhs.  `lhs_eval()` is analogous.

 2. add an argument to `f_eval()` to indicate which side is being evaluated.  Something like

```r
f_eval <- function(x, data = NULL, side = c("right", "left", "both")) {

}
```
where "both" would return a list of length 2.  Or 
```r
f_eval <- function(x, data = NULL, right = TRUE) {   # or left = FALSE

}
```

**Comment by hadley** [comment]
For now, I think I'll do `f_rhs_eval()` and `f_lhs_eval()` and leave `f_eval()` mapped to `f_rhs_eval()`

**Comment by rpruim** [comment]
That seems reasonable.  It won't disrupt old use cases and makes more sense for people applying this to other types of formulas.

Will this make it into the CRAN release coming shortly?  I'm expecting a release of `mosaic` to follow hard on the heals of the release of `lazyeval` and am in the process of converting to the new API.

**Comment by hadley** [comment]
It's scheduled for today :/
