### ISSUE TITLE
differences between expr_text() and expr_label()

### ISSUE THREAD

**Issue by rpruim** [hadley/lazyeval#70]
Are these differences intentional?

```r
foo <- function(x) {
  lx <- lazyeval::f_capture(x)
  c(label = expr_label(x), text = expr_text(x))
}

foo(x)
## label  text 
## "`x`"   "x" 
foo(a ~ b)
##     label      text 
## "`a ~ b`"   "a ~ b" 
```
If so, perhaps this could be documented to explain why.

**Comment by hadley** [comment]
Yes - see the examples?

**Comment by hadley** [comment]
`expr_label()` might be a bit idiosyncratic - it's my style including in error messages

**Comment by rpruim** [comment]
I was just about to type:  the examples show *that* but don't explain *why*.

**Comment by hadley** [comment]
Yeah, I don't think there is a why - just what looks good to my eye.
