### ISSUE TITLE
should f_eval() allow data to be an environment?

### ISSUE THREAD

**Issue by rpruim** [hadley/lazyeval#71]
It would be nice if this worked:
```r
foo <- function(x, data = parent.frame()) {
  lx <- lazyeval::f_capture(x)
  lazyeval::f_eval(lx, data)
}

foo(a ~ b)
##  Error: Do not know how to find data associated with `x` 
foo(5)
##  Error: Do not know how to find data associated with `x` 
```

**Comment by hadley** [comment]
I don't think that's possible - that would introduce two stacks of environments. 

Do you have a more realistic example? The whole point is avoid using `parent.frame()` because it's not reliable.

**Comment by rpruim** [comment]
Actually, I may be able to refactor to avoid this since `f_capture(x)` will capture the environment and I can make the default value of `data` be `NULL`.  I'll see if I can get that to work.
