### ISSUE TITLE
Incompatibility with gdata

### ISSUE THREAD

**Issue by Alanocallaghan** [hadley/lazyeval#85]
The package gdata declares a function called `env` which, if loaded before lazyeval, breaks `f_env` and therefore the syntax of the `plotly` package (via lazyeval).

My understanding is that this could be fixed by changing the `f_env` function from: 
    .Call(env, f)
to:
    .Call("env", f)

But I'm not 100% certain given that my knowledge of native libraries in R is limited. Thanks

**Comment by hadley** [comment]
How are you loading the package? `env` should always be found in the lazyeval namespace.

**Comment by Alanocallaghan** [comment]
Apologies I posted this reprex in #88. `env` is a function in `gdata` but it seems like this issue would exist whenever `env` exists in the environment that lazyeval is loaded into, judging by #84.


    library(gdata)
    library(lazyeval)
    Warning message:
      failed to assign NativeSymbolInfo for env since env is already defined in the ‘lazyeval’ namespace 

    plotly::plot_ly(mtcars, ~a)
    Error in .Call(env, f) : 
      first argument must be a string (of length 1) or native symbol reference

**Comment by Alanocallaghan** [comment]
If lazyeval is loaded after gdata, the problem doesn't occur, but that's not really a robust fix in my opinion

**Comment by hadley** [comment]
Please consolidate everything into #84. I'm going to close this issue.
