### ISSUE TITLE
expr_text and pipes

### ISSUE THREAD

**Issue by ctbrown** [hadley/lazyeval#95]
Given that NSE labeling  follows "a chain of promises back up to the original expression", should it be expected that these are equivalent?

```
f <- function( x )  expr_text(x)

f(mean)    # "mean" 
mean %>% f # "_lhs"
```

**Comment by lionel-** [comment]
I don't think so. This is dependent on magrittr's implementation, which does special tricks to emulate something that really should be part of the language.

**Comment by lionel-** [comment]
@hadley could you give me collaborator rights here please?

**Comment by ctbrown** [comment]
@lionel, 

I am taking your answer to mean that::
- "this is not a **lazyeval** issue" or perhaps more correctly "lazyeval will not support this", and 
- "this might be a **magrittr** issue"   

I don't take you response as and not necessarily that it is an unreasonable expectation that the two function call be equivalent. Is that fair to say?

**Comment by hadley** [comment]
It's not possible because of the way magrittr is implemented; implementing magrittr in such a way that it would work would probably cause different problems.
